apiVersion: v1
kind: PersistentVolume
metadata:
  name: cts-postgresql-pv
spec:
  storageClassName: cts-postgres-manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/k8s-pv