apiVersion: v1
kind: Service
metadata:
  name: cts-postgresql-service
  labels:
    app: cryptostream
    tier: postgresql
spec:
  type: NodePort  
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30000 
  selector:
    app: cryptostream
    tier: postgresql